sudo: false

language: go

services:
  - docker

go:
  - 1.6

branches:
  only:
    - master
    - develop
    - /^fb-\d+$/

install:
  - export GO15VENDOREXPERIMENT=1
  - go get github.com/Masterminds/glide
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - $GOPATH/bin/glide install

script:
  - if [ $(go fmt $($GOPATH/bin/glide novendor) | wc -l) -gt 0 ]; then echo "Files incorrectly formatted" && exit 1; fi
  - go vet -x $($GOPATH/bin/glide novendor)
  - go test -v -race $($GOPATH/bin/glide novendor)
  - $GOPATH/bin/overalls -project=github.com/${TRAVIS_REPO_SLUG} -covermode=count -ignore=.git,vendor,ci -debug
  - VPKG="github.com/${TRAVIS_REPO_SLUG}/version"
  - BUILD_VERSION=$(head -n 1 .semver)
  - CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-X ${VPKG}.Version=${BUILD_VERSION} -X ${VPKG}.Commit=${TRAVIS_COMMIT} -X ${VPKG}.Branch=${TRAVIS_BRANCH}" -o ci/artifacts/urban-gopher-$BUILD_VERSION

after_success:
  - $GOPATH/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci

before_deploy:
  - cp .semver ci/artifacts/
  - openssl aes-256-cbc -K $encrypted_a20232c65bfb_key -iv $encrypted_a20232c65bfb_iv -in ci/deploy_key.enc -out ~/.ssh/id_rsa -d
  - chmod 400 ~/.ssh/id_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: ci/dockerize.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ci/dockerize.sh dev
    on:
      branch: develop

after_deploy:
  - ci/update_develop_version.sh
  - sudo rm ~/.ssh/id_rsa

notifications:
  email:
    recipients:
      - teamurbangopher@gmail.com
    on_success: change
    on_failure: always
  slack:
    secure: yyoesM6sJtJmPm1BZw6OZp7f6rWYjrcuSwRIBzqa+Abr5a53OOcIef88mYOS8LoVtl3mZK5ons2vxk75f0ReulseuLYvSFtmnCoThfvxxw9Tse0odPcYC/n7tIajAp/AfwfBzmdCmGWlvwvSfV0PP/ynBY5TwING3HzG2H+cisfZOza27D9/s1ACruIraz/rDSMixKfeougYAOg4mOaMnobKAPHNbSIk11HkW8A7Xtxynr4jLQT/MkvRoRi+cVRmAR9+6WtIStigguKkjFvZQ4pQxgQ7ZRjOl1vmQKln/dLcD58eXQjs8CWOB7aVEKAUeoH+4a6jxbtVIpb4E2tbaHfwRJO8A3UDRztmWKcp1beb1kGJ9PJg4N7njCv+uf93Kvq5VO2bh8UOdi8tPnILGP+QwUKLd44I1CI6ef5XI/zsg7m0rCIh1KxLm4ngdBRpd1nP321woJev7kK+DwOSd57zyAyRXTZNh/8P7SYPgwUhLEIzJ96AaF9BaWTgrZ6pTrpR/j7Do/8jYy7ZgyZS+x7OUhm9Soia1iZsJ96g7NfKVvOxQ8I7702Uu0tHCTKtqAV9/Yi+ZLBWbz+lhhRMU7+Jfz5FXU7e8keAZbg1stPTEeJLImajVZge5lURFZe0yDR72fqSYKB4itrijOb6hEC0Au3yR9c8culvM5jWYds=
